//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.12.12 at 11:27:47 PM IST
//
package google.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncludeOptionalElements" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReturnCarrierRoute" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Address">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FirmName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Zip5" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Zip4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="USERID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = { "includeOptionalElements", "returnCarrierRoute", "address" } )
@XmlRootElement( name = "AddressValidateRequest" )
public class UspsAddressValidateRequest {

	@XmlElement( name = "IncludeOptionalElements", required = true )
	protected String includeOptionalElements;
	@XmlElement( name = "ReturnCarrierRoute", required = true )
	protected String returnCarrierRoute;
	@XmlElement( name = "Address", required = true )
	protected UspsAddressValidateRequest.Address address;
	@XmlAttribute( name = "USERID" )
	protected String userid;

	/**
	 * Gets the value of the includeOptionalElements property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIncludeOptionalElements()
	{
		return includeOptionalElements;
	}

	/**
	 * Sets the value of the includeOptionalElements property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIncludeOptionalElements( String value )
	{
		this.includeOptionalElements = value;
	}

	/**
	 * Gets the value of the returnCarrierRoute property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReturnCarrierRoute()
	{
		return returnCarrierRoute;
	}

	/**
	 * Sets the value of the returnCarrierRoute property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReturnCarrierRoute( String value )
	{
		this.returnCarrierRoute = value;
	}

	/**
	 * Gets the value of the address property.
	 * 
	 * @return possible object is {@link UspsAddressValidateRequest.Address }
	 * 
	 */
	public UspsAddressValidateRequest.Address getAddress()
	{
		return address;
	}

	/**
	 * Sets the value of the address property.
	 * 
	 * @param value
	 *            allowed object is {@link UspsAddressValidateRequest.Address }
	 * 
	 */
	public void setAddress( UspsAddressValidateRequest.Address value )
	{
		this.address = value;
	}

	/**
	 * Gets the value of the userid property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUSERID()
	{
		return userid;
	}

	/**
	 * Sets the value of the userid property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUSERID( String value )
	{
		this.userid = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="FirmName" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Zip5" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="Zip4" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}byte" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD )
	@XmlType( name = "", propOrder = { "firmName", "address1", "address2", "city", "state", "zip5", "zip4" } )
	public static class Address {

		@XmlElement( name = "FirmName", required = true )
		protected String firmName;
		@XmlElement( name = "Address1", required = true )
		protected String address1;
		@XmlElement( name = "Address2", required = true )
		protected String address2;
		@XmlElement( name = "City", required = true )
		protected String city;
		@XmlElement( name = "State", required = true )
		protected String state;
		@XmlElement( name = "Zip5" )
		protected String zip5;
		@XmlElement( name = "Zip4", required = true )
		protected String zip4;
		@XmlAttribute( name = "ID" )
		protected Byte id;

		/**
		 * Gets the value of the firmName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFirmName()
		{
			return firmName;
		}

		/**
		 * Sets the value of the firmName property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFirmName( String value )
		{
			this.firmName = value;
		}

		/**
		 * Gets the value of the address1 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAddress1()
		{
			return address1;
		}

		/**
		 * Sets the value of the address1 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setAddress1( String value )
		{
			this.address1 = value;
		}

		/**
		 * Gets the value of the address2 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAddress2()
		{
			return address2;
		}

		/**
		 * Sets the value of the address2 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setAddress2( String value )
		{
			this.address2 = value;
		}

		/**
		 * Gets the value of the city property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCity()
		{
			return city;
		}

		/**
		 * Sets the value of the city property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCity( String value )
		{
			this.city = value;
		}

		/**
		 * Gets the value of the state property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getState()
		{
			return state;
		}

		/**
		 * Sets the value of the state property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setState( String value )
		{
			this.state = value;
		}

		/**
		 * Gets the value of the zip5 property.
		 * 
		 */
		public String getZip5()
		{
			return zip5;
		}

		/**
		 * Sets the value of the zip5 property.
		 * 
		 */
		public void setZip5( String value )
		{
			this.zip5 = value;
		}

		/**
		 * Gets the value of the zip4 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getZip4()
		{
			return zip4;
		}

		/**
		 * Sets the value of the zip4 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setZip4( String value )
		{
			this.zip4 = value;
		}

		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible object is {@link Byte }
		 * 
		 */
		public Byte getID()
		{
			return id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 * @param value
		 *            allowed object is {@link Byte }
		 * 
		 */
		public void setID( Byte value )
		{
			this.id = value;
		}

	}

}
